<?xml version="1.0"?>
<package format="3">
  <name>assistant_bringup</name>
  <version>0.1.0</version>
  <description>Launch files and parameter configuration for the assistant robot.</description>
  <maintainer email="todo@example.com">mythos</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>assistant_audio</exec_depend>
  <exec_depend>assistant_brain</exec_depend>
  <exec_depend>assistant_commands</exec_depend>
  <exec_depend>assistant_robot</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
